### ISSUE TITLE
Not turning lights off properly

### ISSUE THREAD

**Issue by jacobhallgren** [leifmariposa/fjaraskupan#3]
Sometimes when I turn off the light from home assistant, the fan dims to like 2%. But does not turn off the light. This never happens from the official app.

**Comment by leifmariposa** [comment]
I have noticed the same. To switch off I send dim-level zero, but I suspect there might be a seperate switch off command. 
This means to set up capturing of bluetooth communication between app and fjäråskupan, something like here https://support.honeywellaidc.com/s/article/How-to-capture-Bluetooth-traffic-from-and-to-an-Android-Device
Will do sometime when I have the time for it...

**Comment by jacobhallgren** [comment]
Maybe you can find the right command here? 

https://github.com/elupus/fjaraskupan/blob/master/src/fjaraskupan/__init__.py

**Comment by jacobhallgren** [comment]
> I have noticed the same. To switch off I send dim-level zero, but I suspect there might be a seperate switch off command. This means to set up capturing of bluetooth communication between app and fjäråskupan, something like here https://support.honeywellaidc.com/s/article/How-to-capture-Bluetooth-traffic-from-and-to-an-Android-Device Will do sometime when I have the time for it...

Maybe you can find the right command here:

https://github.com/elupus/fjaraskupan/blob/master/src/fjaraskupan/__init__.py

**Comment by leifmariposa** [comment]
@jacobhallgren Try this, seems to work! I'm using a toggle command for to switch off the light and I think it will not have any sideeffects where it turns the light on when it shouldn't.

**Comment by jacobhallgren** [comment]
@leifmariposa Is it not possible to send a off command? Sometimes the pi misses a command and HA think that the light/fan is off when it's not. Is it possible to make ha force refresh and poll the state of the hob?

**Comment by leifmariposa** [comment]
Haven't found any off command, therefore the toggle command. After every command sent there is a delay and then the state is read to update HA.

**Comment by jacobhallgren** [comment]
@leifmariposa Ok, So the "original" app sends a toggle command for on /off? Yes but can I somehow trigger that update via a call or so from HA? Since it gets it wrong sometimes.

**Comment by leifmariposa** [comment]
Yes! If you install button-card in HACS, then you could add a custom button card that calls the fan light service, like this:

type: custom:button-card
name: Toggle fan light
tap_action:
  action: call-service
  service: shell_command.set_kitchen_fan_light
  service_data:
    value: 0

This will toggle the light on/off. If you change the value to something other than zero, it will be set to that value.
If you have any other control for the fan light, e. g. a slider, it will be updated after a little while after that you have called the service.

Just a thought, if it gets it wrong sometimes maybe the raspberry pi isn't close enough to the fan? Mine is about three meters away and I rearly have communication problems.

**Comment by jacobhallgren** [comment]
@leifmariposa Ok, I wanna update the status without doing anything to the light. How can I do that? "just read the status" The pi is close to it. Like 2 meters.

**Comment by jacobhallgren** [comment]
@leifmariposa Also one problem with the toggle is that if your have scenes that turn off all for example in the night. If the hob is already off HA still sends a toggle command which turns the hob on. Would be nice if you could add some logic for it to not send toggle if the state that its trying to archive already is met.

**Comment by jacobhallgren** [comment]
@leifmariposa Appreciate your work, would be great if you could make some kind of check for the toggle command.
